language: python

os: linux
dist: xenial
arch: arm64

services:
  - docker

# before_install:
#   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#   - sudo apt-get -q update
#   - sudo apt-get -y install gcc-4.8

script:
  - docker build -t oddlyshapeddog/collectionbot .
  - docker run -d oddlyshapeddog/collectionbot --name cb
  - ./tests/test.sh $DISCORD_WEKHOOK_URL_CANARY
  - docker stop cb

after_success:
  - echo "Success"
  - ./travis/send-discord-notification.sh success $DISCORD_WEBHOOK_URL_BUILDS
after_failure:
  - echo "Failure"
  - ./travis/send-discord-notification.sh failure $DISCORD_WEBHOOK_URL_BUILDS
